name: leap_analytics
version: 1.0.0
profile: default

model-paths: ["models"]
macro-paths: ["macros"]

models:
  leap_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
